DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        nationality VARCHAR(255)
);

CREATE TABLE BOOK (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      genre VARCHAR(100),
                      price DOUBLE,
                      author_id BIGINT,
                      CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES AUTHOR(id)
);
